pipeline {
    agent {
        docker {
            image 'ruby',
            args '--link selenium'
        }
    }
    stages {
        stage('Preparation') {
            steps {
                sh "cd tests; bundle install"
            }
        }
        stage('Run Tests') {
            steps {
                sh "cd tests; cucumber -p sandbox -t @smoke"
            }
        }
    }
}